// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package A

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackendAClient is the client API for BackendA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendAClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type backendAClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendAClient(cc grpc.ClientConnInterface) BackendAClient {
	return &backendAClient{cc}
}

func (c *backendAClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/backend_a.BackendA/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendAServer is the server API for BackendA service.
// All implementations must embed UnimplementedBackendAServer
// for forward compatibility
type BackendAServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedBackendAServer()
}

// UnimplementedBackendAServer must be embedded to have forward compatible implementations.
type UnimplementedBackendAServer struct {
}

func (UnimplementedBackendAServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedBackendAServer) mustEmbedUnimplementedBackendAServer() {}

// UnsafeBackendAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendAServer will
// result in compilation errors.
type UnsafeBackendAServer interface {
	mustEmbedUnimplementedBackendAServer()
}

func RegisterBackendAServer(s grpc.ServiceRegistrar, srv BackendAServer) {
	s.RegisterService(&BackendA_ServiceDesc, srv)
}

func _BackendA_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendAServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend_a.BackendA/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendAServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendA_ServiceDesc is the grpc.ServiceDesc for BackendA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend_a.BackendA",
	HandlerType: (*BackendAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _BackendA_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "A/api.proto",
}
