// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package B

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BackendBClient is the client API for BackendB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackendBClient interface {
	SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeReply, error)
}

type backendBClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendBClient(cc grpc.ClientConnInterface) BackendBClient {
	return &backendBClient{cc}
}

func (c *backendBClient) SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeReply, error) {
	out := new(ByeReply)
	err := c.cc.Invoke(ctx, "/backend_b.BackendB/SayBye", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendBServer is the server API for BackendB service.
// All implementations must embed UnimplementedBackendBServer
// for forward compatibility
type BackendBServer interface {
	SayBye(context.Context, *ByeRequest) (*ByeReply, error)
	mustEmbedUnimplementedBackendBServer()
}

// UnimplementedBackendBServer must be embedded to have forward compatible implementations.
type UnimplementedBackendBServer struct {
}

func (UnimplementedBackendBServer) SayBye(context.Context, *ByeRequest) (*ByeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayBye not implemented")
}
func (UnimplementedBackendBServer) mustEmbedUnimplementedBackendBServer() {}

// UnsafeBackendBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendBServer will
// result in compilation errors.
type UnsafeBackendBServer interface {
	mustEmbedUnimplementedBackendBServer()
}

func RegisterBackendBServer(s grpc.ServiceRegistrar, srv BackendBServer) {
	s.RegisterService(&BackendB_ServiceDesc, srv)
}

func _BackendB_SayBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendBServer).SayBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend_b.BackendB/SayBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendBServer).SayBye(ctx, req.(*ByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendB_ServiceDesc is the grpc.ServiceDesc for BackendB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backend_b.BackendB",
	HandlerType: (*BackendBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayBye",
			Handler:    _BackendB_SayBye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "B/api.proto",
}
